require('./easy/isPrime')
require('./easy/factorial')
require('./easy/fib')
require('./easy/isSorted')
require('./easy/filter')
require('./easy/reduce')
require('./easy/reverse')
require('./easy/indexOf')
require('./easy/missing')
require('./easy/isPalindrome')

